### ISSUE TITLE
实例方法的检查还不支持

### ISSUE THREAD

**Issue by sky-admin** [mpx-ecology/mpx-es-check#1]
[1,2,3].includes(2)
这种代码不会认为有问题

**Comment by Blackgan3** [comment]
加下 --all 就会检测实例方法了，因为会存在误判情况

**Comment by sky-admin** [comment]
并没有啊，试试在 tests/es5.js里多加一行 [1,2,3].includes(2)，然后执行：
./index.js --all -e 6 ./tests/es5.js
![image](https://user-images.githubusercontent.com/6292668/101620745-e0023300-3a4f-11eb-8cc4-dc5d4182650f.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/101622120-9d415a80-3a51-11eb-83a3-a9c394d417e5.png)
被注释掉了？

**Comment by Blackgan3** [comment]
嗯嗯，这里之前挪到了 callExpression 中做判断，不过确实有问题，我修改下

**Comment by Blackgan3** [comment]
0.0.13 版本你再试下，我修复发布了
